[package]
name = "solana-sdk-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.0"
anyhow = "1.0.83"
bip39 = "2.0.0"
dotenv = "0.15.0"
solana-client = "1.18.12"
solana-sdk = "1.18.12"
tokio = { version = "1.37.0", features = ["full"] }
